log_details = false
demo_input = true
demo_output = true
demo_limit = 100
sync_url_dolib = 'https://crm.himopt71.ru/api/index.php'
sync_url_fresh = 'https://msk1.1cfresh.com/a/ea/3023505/ru_RU/odata/standard.odata'
sync_dir_dolib2fresh = true
sync_dir_fresh2dolib = true
sync_requests_delay = 1